apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: {{ include "osouji-system.fullname" . }}-backend
  labels:
    app: {{ include "osouji-system.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "osouji-system.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "osouji-system.fullname" . }}-backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: password
            - name: ConnectionStrings__osouji-db
              value: "Host=$(DB_HOST);Port=$(DB_PORT);Database=$(DB_NAME);Username=$(DB_USER);Password=$(DB_PASSWORD)"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://monitoring-alloy.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_SERVICE_NAME
              value: {{ include "osouji-system.fullname" . }}-backend
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.namespace.name=$(MY_NAMESPACE),k8s.pod.name=$(MY_POD_NAME)"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: {{ include "osouji-system.fullname" . }}-frontend
  labels:
    app: {{ include "osouji-system.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "osouji-system.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "osouji-system.fullname" . }}-frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}