---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-auth-secret
spec:
  encryptedData:
    password: AgB5HaMTpVj+q8UPbEF0IeeJkbzhs6q46+BpCTtL9qEAn5xWzexHZp3mI/IDHT8lDQOn8fgdXkjKihXe3/RzXNBQc7fhBvZX5CZXSmAjXwG6S3HXrj2i8mkUZufihtdNexqOxWQ/Mob+8Guo7kDYmc1x8Idm0du5OvcsEwTdIiMx668MJAdLuj4GQH50OpyGG6ox+vXcj3+lbqikoFHa82cBYXLjW01bpnjnT4PDrvmdpFuyqHITGr8uY2TdyJwAF9ymoTehkx7vBzuZAq8nBg2fF43P+0xJXRgGVJOXIiDuOWlGSm2BrVSWjpLfIO8/Vp6vTyjHZL7e5XqmxNLGa9nPtWylGL4SXkW63Mu+5VRe31uFp4/ldERjiSzGKGW8UpnKG5I9LVtyyJgVKmCd6aITaj2/LGUl/zLmSS/O7xJT0+bYiTYTVV2m2Hy2RGDmEZrdeizge+9NKcN+Biq1/JwpIkPEF2BgxpEfxfMxJATmHhtmp7hNWWOdQBXpuo942e4IEKOIJ2q8nic95qr5rHKI/ubzZLUs01M19otH5KZ8NyQszB98w3yot5m2qBwf0V94NRg+pvDKHS7VcAimZBwsvZmFFTlsXUm80tVBkd3rSm94Te+AM2/8sxd9AYnurw/j0BqFIOR+VkVzGN0EtNUfG9y/meEvlT5/coiUM7DTHn159JNg6BOHn1DRIFkNKu/N/BlcApqtefYcphE=
    postgres-password: AgB5DSGs2n2rEHZwUnwPS8yRjrZW+97ziesKYJ8y1AteTwC7kBdolAiXCXrc5/rrSr/+hu8yO1+wjUv+qDsfnCtqmOgZ4GNC7d9w2hMuRc/cdgpe9fdunjL/z4KeobQL6FNGLbbnAWGpI/tBpeFIzy6zJddlltNYPel40ARCmVLdMcxc8DJKnI+kkmUdM395axZ7LtPoLDaeRhPa+S+tiZZmUN3h9u1N9fUN4sdaCSF8Px3zMiTkt5uDKzbulBAnbiK+XbicCoaiZXRc1sxBq1649iSlRO2HDKjg4XBLt6RY145NFZbVk85wDcOTeOLrEM8w+mqj0hj0kSl0EwiJEuC96DZ1QJiqlZ4yKUSQxsUO1s71DpQI8t9YtD+X69r50zhoyTi99HQzltrFanOTPKih0OE2aZXgVzy3mDkwo1UDT+yqYfHTup7cA9kxCq7YknQFTkUaMGP2XOb07isttVfEHdVBEHEsBYkG8TaFmjuy+hbLBby86PRef2q4XindWjMVCDu2v0v9BhJNeLyTPdJTn8sTGLhLfImYormUmOtO+3YmGWWRvTpQ+kR2xKdU93N3X6+xwvhRguqEaaHOGgTohWySQMApgcY13nYDCvVue6yHW/tjDNxOB8CHtSqt/JNFHMZUlrK8ao4+84LdttL/s4cArgZdFXu8Y/BKtRbxBzB89QHH0pkvlTaj0nFaxW1Gs6uDD/GzYz2S2CcfYfDNqQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-auth-secret
