/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWeeklyDutyPlansRouteImport } from './routes/_app/weekly-duty-plans'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppFacilitiesRouteImport } from './routes/_app/facilities'
import { Route as AppCleaningAreasRouteImport } from './routes/_app/cleaning-areas'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeeklyDutyPlansRoute = AppWeeklyDutyPlansRouteImport.update({
  id: '/weekly-duty-plans',
  path: '/weekly-duty-plans',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppFacilitiesRoute = AppFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AppRoute,
} as any)
const AppCleaningAreasRoute = AppCleaningAreasRouteImport.update({
  id: '/cleaning-areas',
  path: '/cleaning-areas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/cleaning-areas': typeof AppCleaningAreasRoute
  '/facilities': typeof AppFacilitiesRoute
  '/users': typeof AppUsersRoute
  '/weekly-duty-plans': typeof AppWeeklyDutyPlansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/cleaning-areas': typeof AppCleaningAreasRoute
  '/facilities': typeof AppFacilitiesRoute
  '/users': typeof AppUsersRoute
  '/weekly-duty-plans': typeof AppWeeklyDutyPlansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/_app/cleaning-areas': typeof AppCleaningAreasRoute
  '/_app/facilities': typeof AppFacilitiesRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/weekly-duty-plans': typeof AppWeeklyDutyPlansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/cleaning-areas'
    | '/facilities'
    | '/users'
    | '/weekly-duty-plans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/cleaning-areas'
    | '/facilities'
    | '/users'
    | '/weekly-duty-plans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/dashboard'
    | '/_app/cleaning-areas'
    | '/_app/facilities'
    | '/_app/users'
    | '/_app/weekly-duty-plans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weekly-duty-plans': {
      id: '/_app/weekly-duty-plans'
      path: '/weekly-duty-plans'
      fullPath: '/weekly-duty-plans'
      preLoaderRoute: typeof AppWeeklyDutyPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facilities': {
      id: '/_app/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AppFacilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cleaning-areas': {
      id: '/_app/cleaning-areas'
      path: '/cleaning-areas'
      fullPath: '/cleaning-areas'
      preLoaderRoute: typeof AppCleaningAreasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCleaningAreasRoute: typeof AppCleaningAreasRoute
  AppFacilitiesRoute: typeof AppFacilitiesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWeeklyDutyPlansRoute: typeof AppWeeklyDutyPlansRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCleaningAreasRoute: AppCleaningAreasRoute,
  AppFacilitiesRoute: AppFacilitiesRoute,
  AppUsersRoute: AppUsersRoute,
  AppWeeklyDutyPlansRoute: AppWeeklyDutyPlansRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
