-- Infrastructure DDL Draft v1
-- Source ADR:
-- - docs/infrastructure-architecture-adr-v2.md
-- - docs/infrastructure-architecture-adr-v3.md

-- Required extension for UUID defaults.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- Event Sourcing Core
-- ============================================================================

CREATE TABLE IF NOT EXISTS event_store_events (
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    stream_id UUID NOT NULL,
    stream_type TEXT NOT NULL CHECK (stream_type IN ('cleaning_area', 'weekly_duty_plan')),
    stream_version BIGINT NOT NULL CHECK (stream_version > 0),
    global_position BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_type TEXT NOT NULL,
    event_schema_version INT NOT NULL CHECK (event_schema_version > 0),
    payload JSONB NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_event_stream_version UNIQUE (stream_id, stream_version),
    CONSTRAINT uq_event_global_position UNIQUE (global_position)
);

CREATE INDEX IF NOT EXISTS ix_event_store_events_stream
    ON event_store_events (stream_type, stream_id, stream_version DESC);

CREATE INDEX IF NOT EXISTS ix_event_store_events_recorded_at
    ON event_store_events (recorded_at);

CREATE TABLE IF NOT EXISTS event_store_snapshots (
    stream_id UUID PRIMARY KEY,
    stream_type TEXT NOT NULL CHECK (stream_type IN ('cleaning_area', 'weekly_duty_plan')),
    last_included_version BIGINT NOT NULL CHECK (last_included_version > 0),
    snapshot_payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_event_store_snapshots_updated_at
    ON event_store_snapshots (updated_at DESC);

-- ============================================================================
-- Outbox
-- ============================================================================

CREATE TABLE IF NOT EXISTS outbox_messages (
    message_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_event_id UUID NOT NULL REFERENCES event_store_events(event_id),
    exchange_name TEXT NOT NULL,
    routing_key TEXT NOT NULL,
    payload JSONB NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ NULL,
    attempt_count INT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_outbox_source_event UNIQUE (source_event_id)
);

CREATE INDEX IF NOT EXISTS ix_outbox_messages_unpublished
    ON outbox_messages (published_at, available_at);

CREATE INDEX IF NOT EXISTS ix_outbox_messages_created_at
    ON outbox_messages (created_at DESC);

-- ============================================================================
-- Projections
-- ============================================================================

CREATE TABLE IF NOT EXISTS projection_cleaning_areas (
    area_id UUID PRIMARY KEY,
    area_name TEXT NOT NULL,
    current_week_rule JSONB NOT NULL,
    pending_week_rule JSONB NULL,
    rotation_cursor INT NOT NULL,
    aggregate_version BIGINT NOT NULL CHECK (aggregate_version > 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS projection_area_members (
    area_id UUID NOT NULL,
    user_id UUID NOT NULL,
    area_member_id UUID NOT NULL,
    employee_number CHAR(6) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_projection_area_members PRIMARY KEY (area_id, user_id),
    CONSTRAINT ck_projection_area_members_employee_number_format
        CHECK (employee_number ~ '^[0-9]{6}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_projection_area_members_user_active
    ON projection_area_members (user_id)
    WHERE is_active = true;

CREATE INDEX IF NOT EXISTS ix_projection_area_members_area_active
    ON projection_area_members (area_id)
    WHERE is_active = true;

CREATE TABLE IF NOT EXISTS projection_weekly_plans (
    plan_id UUID PRIMARY KEY,
    area_id UUID NOT NULL,
    week_year INT NOT NULL CHECK (week_year >= 2000),
    week_number INT NOT NULL CHECK (week_number BETWEEN 1 AND 53),
    revision INT NOT NULL CHECK (revision >= 1),
    status SMALLINT NOT NULL CHECK (status IN (0, 1, 2)),
    fairness_window_weeks INT NOT NULL CHECK (fairness_window_weeks > 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_projection_weekly_plans_area_week UNIQUE (area_id, week_year, week_number)
);

CREATE INDEX IF NOT EXISTS ix_projection_weekly_plans_area_week_updated
    ON projection_weekly_plans (area_id, week_year, week_number, updated_at DESC);

CREATE TABLE IF NOT EXISTS projection_weekly_plan_assignments (
    plan_id UUID NOT NULL,
    revision INT NOT NULL CHECK (revision >= 1),
    spot_id UUID NOT NULL,
    user_id UUID NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_projection_weekly_plan_assignments PRIMARY KEY (plan_id, spot_id),
    CONSTRAINT fk_projection_weekly_plan_assignments_plan
        FOREIGN KEY (plan_id) REFERENCES projection_weekly_plans(plan_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_projection_weekly_plan_assignments_user
    ON projection_weekly_plan_assignments (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS projection_weekly_plan_offduty (
    plan_id UUID NOT NULL,
    revision INT NOT NULL CHECK (revision >= 1),
    user_id UUID NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_projection_weekly_plan_offduty PRIMARY KEY (plan_id, user_id),
    CONSTRAINT fk_projection_weekly_plan_offduty_plan
        FOREIGN KEY (plan_id) REFERENCES projection_weekly_plans(plan_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_projection_weekly_plan_offduty_user
    ON projection_weekly_plan_offduty (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS projection_user_weekly_workloads (
    area_id UUID NOT NULL,
    user_id UUID NOT NULL,
    week_year INT NOT NULL CHECK (week_year >= 2000),
    week_number INT NOT NULL CHECK (week_number BETWEEN 1 AND 53),
    assigned_count INT NOT NULL CHECK (assigned_count >= 0),
    off_duty_count INT NOT NULL CHECK (off_duty_count IN (0, 1)),
    source_plan_id UUID NOT NULL,
    source_revision INT NOT NULL CHECK (source_revision >= 1),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_projection_user_weekly_workloads
        PRIMARY KEY (area_id, user_id, week_year, week_number),
    CONSTRAINT fk_projection_user_weekly_workloads_plan
        FOREIGN KEY (source_plan_id) REFERENCES projection_weekly_plans(plan_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_projection_user_weekly_workloads_area_week
    ON projection_user_weekly_workloads (area_id, week_year, week_number);

CREATE INDEX IF NOT EXISTS ix_projection_user_weekly_workloads_user_week
    ON projection_user_weekly_workloads (user_id, week_year, week_number);

CREATE TABLE IF NOT EXISTS projection_checkpoints (
    projector_name TEXT PRIMARY KEY,
    last_global_position BIGINT NOT NULL CHECK (last_global_position >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Cache Invalidation Recovery
-- ============================================================================

CREATE TABLE IF NOT EXISTS cache_invalidation_tasks (
    task_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cache_key TEXT NOT NULL,
    reason_global_position BIGINT NOT NULL CHECK (reason_global_position >= 0),
    retry_count INT NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_error TEXT NULL,
    resolved_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cache_invalidation_tasks_key_reason
    ON cache_invalidation_tasks (cache_key, reason_global_position);

CREATE INDEX IF NOT EXISTS ix_cache_invalidation_tasks_pending
    ON cache_invalidation_tasks (next_retry_at)
    WHERE resolved_at IS NULL;

-- ============================================================================
-- Messaging Idempotency & Retention Audit
-- ============================================================================

CREATE TABLE IF NOT EXISTS consumer_processed_events (
    consumer_name TEXT NOT NULL,
    event_id UUID NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_consumer_processed_events PRIMARY KEY (consumer_name, event_id)
);

CREATE INDEX IF NOT EXISTS ix_consumer_processed_events_processed_at
    ON consumer_processed_events (processed_at DESC);

CREATE TABLE IF NOT EXISTS data_retention_purge_reports (
    report_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_name TEXT NOT NULL,
    target_table TEXT NOT NULL,
    purge_from TIMESTAMPTZ NOT NULL,
    purge_to TIMESTAMPTZ NOT NULL,
    deleted_rows BIGINT NOT NULL CHECK (deleted_rows >= 0),
    status TEXT NOT NULL CHECK (status IN ('succeeded', 'failed')),
    error_message TEXT NULL,
    executed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_data_retention_purge_reports_executed_at
    ON data_retention_purge_reports (executed_at DESC);
