replicaCount: 1

hostname: osouji-system.local

frontend:
  image:
    repository: ghcr.io/user/frontend
    tag: latest
  service:
    type: ClusterIP
    port: 80
  resources: {}
backend:
  image:
    repository: ghcr.io/user/backend
    tag: latest
  service:
    type: ClusterIP
    port: 8080
  resources: {}
postgresql:
  enabled: true
  auth:
    database: osouji-db
    username: user
    existingSecret: postgres-auth-secret
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
