---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-auth-secret
spec:
  encryptedData:
    password: AgASQYM9y26YeALOlyuMGPIxBiXP04CpVkTBaEn2yCQz5clj/wRAed/hzVCRTPDQon3mwhZyHl6To8ETGWkuqI0ea82cFpm99G6E715BmqYIeLssVgdS9qYHh6xX2zXJkk1BbkywQK/MEfailCfCygujOle0EVH555BsU133KGb/awgwlM+DQfWl7KBj2Stn+5S8STte5VhAqxGFZOylM8hoHk3pY0rKwWh1Xnatgy7DSM0Z9Vf7nBqFG6lBY2fQeqax5u8Fu+8kZbQxQZs4ZUt9moHqi0FjTU4wI0hAApUQwZGNJwv3/57l1OSRiXoGfHBSC+GIa4wNLyUNPDi9hRH/lQtvHh++5x9I3flZzCTFgckvWkGk1rczGx4rcG3Eqw0n9PfedrlmBYsgj9PymtMHT0qiwLZadOun4n0foM8QRXnb1u4gW+sePvTKrm7xt3AJSGSJ3QKWrSaHk68YwRhqMooidm/Vbn3PpFtvGgBwfom1NNt4ubPlBVHqvJCOQq2fojNdHxtLPOv8K3UZsoRClJPOTooGQb3U5+jSE4q9Cwi2p3eaa4D+tutrJIg6Ylhlfb9YiMNV471RiR2EUYSzXuDtRxj3TJfuciChP9a7zXz0otksn0QUvqHFAm3EHZgoAf3U58O3kP925DOJ7K8Dk6eqhJEDHkGvxD62EwS8pA+Lkft8/Dk0WIBbYv3Z06pCURxmvz3+U2oVELc=
    postgres-password: AgACqM6ETx7E0rk/5JDS7owbRPNMssrdVO0S3H2cvj2wsqYQmUG0xuAnd1VhCuryToIxTPLFM+u7VNMAPbnPUzMZeuSAa6uvdq4A79f9+pdlFSXNNDqZD0ELzPMNa8bP0CxhTboxyjHmaXNo1smfICwiAx81DSWf6a1HrOIFBL8bGT+Ov70kQXe7EdcdblmmPYrFOQX0FuAuCX8jy5op9qhcxK2B2GgzQzzfV5GqPDGMjzH1brZ6T38Z1eCQweILJqxJ5s9eZRCqA4f4CPwpp7UgKPBlI6n8HC1lq1aPtkCM36rbJSBe6s+LwQ79LClQctDoMCht9xIFKZbCE9xFLI74zQ4lWZDTM3V21FTfUyPB5tG+BrqqkeeQ81RQ0XiO26ukDRMBNuWPE4pWf9KIx26uUkMCF22JlG+R9WZNzhINXy7wTlAsrjcatQ5N60cVs0e/6+3VG15HpKOKMYvbObxXM6mSUHXNGhAYyAJV/eHBbl9m1KVl+oXE3CBl2GwFrzwOvMuXlCjY5zs7I+2hH5boOMcZYdlYDua1GKtKrx82wfcRMkySVnXoufpqQ2JmQdVyVV6TIvWzfDJfCzG20ZmsgwcJ9ND20rBhM7EDNGiz/o7IPwhAB0OEecHdct5tp42U6WL0Rwoou+JZZuDIsGUFS3XI2rjG1WV0cEWXlYHNFOX+iTQB92bQitu6M4M4layA858Mm5I66PWWY8e7ZTyGIg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-auth-secret
